### ISSUE TITLE
Game Barely Runs With A Good PC

### ISSUE THREAD

**Issue by ThornerUA** [cyberstrawberry101/Omega-Adventure-Pack#10]
So I have 32 gigs of ram and dedicated 10 of them for the modpack, it uses about 30~40% of it and with all settings on lowest(Peaceful difficulty, 2 chunk render distance) it still barely runs, this is the only game I have this issue with please help

**Comment by cyberstrawberry101** [comment]
This is a duplicate of issue https://github.com/cyberstrawberry101/Omega-Adventure-Pack/issues/1#issue-550571168

Your graphics card and RAM have no impact on game performance / framerate.  Your single-core CPU speed has the largest impact on performance with this modpack.  Please provide us with the single-core frequency speed of your gaming computer's CPU.

**Comment by ThornerUA** [comment]
Processor: Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz 3.60 GHz

**Comment by cyberstrawberry101** [comment]
@ErickThePresident @powerhungryring 
This is unusual behavior.  Please look further into this.

**Comment by powerhungryring** [comment]
did you make any modifications to the pack

**Comment by ThornerUA** [comment]
No, I haven't done anything to the modpack besides downloading it
