### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by turkay01** [cyberstrawberry101/Omega-Adventure-Pack#11]
[crash-2020-02-04_21.22.53-client.txt](https://github.com/cyberstrawberry101/Omega-Adventure-Pack/files/4155174/crash-2020-02-04_21.22.53-client.txt)

I set the ram to 12and my java is 64and I select it there my graphics card is 1660 ti.
thanks for your help

**Comment by powerhungryring** [comment]
reinstall the modpack. one of the core files got messed up

**Comment by turkay01** [comment]
İ did

**Comment by powerhungryring** [comment]
go into the files and manually delete it. doing it threw technic isnt the best

**Comment by turkay01** [comment]
Ok i will try thx for helping🙃

**Comment by turkay01** [comment]
[crash-2020-02-04_22.30.41-client.txt](https://github.com/cyberstrawberry101/Omega-Adventure-Pack/files/4155536/crash-2020-02-04_22.30.41-client.txt)

**Comment by turkay01** [comment]
https://github.com/cyberstrawberry101/Omega-Adventure-Pack/files/4155536/crash-2020-02-04_22.30.41-client.txt
This is the new crash report
Thx for your help

**Comment by turkay01** [comment]
https://github.com/cyberstrawberry101/Omega-Adventure-Pack/files/4155536/crash-2020-02-04_22.30.41-client.txt
This is the new crash report
Thx for your help

**Comment by turkay01** [comment]
can you help me

**Comment by turkay01** [comment]
help
