### ISSUE TITLE
Modpack doesn't work with traditional launchers

### ISSUE THREAD

**Issue by Explodingcr** [cyberstrawberry101/Omega-Adventure-Pack#14]
Please enable the modpack to work with regular Minecraft launcher, since Technic Launcher doesn't work with recent openjdk, and up to date distros like Debian don't ship old openjdk anymore.

* OS: Debian testing
* OpenJDK: tried with 11 and 13.

**Comment by powerhungryring** [comment]
This is not really our problem its more your os and java, Bring this up to technic for them to look at. I must point out you can download this github and all the mods, scripts, and configs are here for you to throw into the vanilla launcher. Youll have to know how to add forge 1.7.10
