### ISSUE TITLE
Naga death animation crash

### ISSUE THREAD

**Issue by Xodias** [cyberstrawberry101/Omega-Adventure-Pack#36]
Killing the naga will cause a crash when it plays two death animations at the same time. Disabling culling tweaks fixes this. 

`enableCullingTweaks = false`

Crashlog provided if you wanted to look at it yourself. I also provided the config that fixed the crash. Change the file extension on the fastcraft config from .txt to .ini to use it in the pack.

[crash-2020-06-11_15.06.50-client.txt](https://github.com/ErickThePresident/Omega-Adventure-Pack/files/4767088/crash-2020-06-11_15.06.50-client.txt)
[fastcraft.txt](https://github.com/ErickThePresident/Omega-Adventure-Pack/files/4767093/fastcraft.txt)

**Comment by Xodias** [comment]
Could be related to #3 , but they provided no information on the crash

**Comment by EverSoul** [comment]
Issued is fixed. Thanks for providing the info.
