### ISSUE TITLE
what's the clown mod?

### ISSUE THREAD

**Issue by edgardeivis** [cyberstrawberry101/Omega-Adventure-Pack#40]
https://www.youtube.com/watch?v=8-oMqMSe6rc
there is a clown mod (i don't even know if it's a mod) and i really want it (why you ask(because it's fun))

**Comment by gamingpro2248** [comment]
im also looking for the mod

**Comment by TumbleBee6** [comment]
Me too.

**Comment by Explodingcr** [comment]
This is not the right place for socksfor1 content, this is for the omega adventure modpack.
