### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by HeroDrakeor** [cyberstrawberry101/Omega-Adventure-Pack#50]
So i was playing a bit of Minecraft, and decided to play the modpack. I try to boot it up, but it dies constantly when stage 3 is about to start. It was working fine every other time, but it does not want to boot now. Here is the crash report:
[crash-2020-11-15_10.01.43-client.txt](https://github.com/ErickThePresident/Omega-Adventure-Pack/files/5542865/crash-2020-11-15_10.01.43-client.txt)
I know the modpack makers are busy people, so take your time if it really is a bug. It happens no matter what i do. I might see if rebooting my computer helps. In case it affects anything, yes the modpack is in a separate directory from the default one. Yes, it does have 8 gigs or more of RAM. again, it was working until today. If you need any other info, just put a comment and I will try to answer to the best of my ability.

EDIT 1: Rebooting does not help. :\

**Comment by ErickVerlangieri** [comment]
Try uninstalling and install from scratch.

**Comment by HeroDrakeor** [comment]
Nvm, it was something in the files :\
