### ISSUE TITLE
Cant install the modpack, get an error

### ISSUE THREAD

**Issue by BeanTheBoy** [cyberstrawberry101/Omega-Adventure-Pack#57]
when i try to install the modpack it comes up with an error saying: htps://omega.bhweb.ws/omega.zip. please consult the modpack author, i have seen other people have the same problem and wanted to know if anyone has a fix for it?

**Comment by RaveTr** [comment]
Looks like your client can't connect to the server correctly, I presume. I'm not a dev, but I do have the zip folder to upload if you want. But I think it is broken, as when I start it it doesn't create a session.lock file and then says it doesn't have access to it for some reason. It then crashes the server.
