### ISSUE TITLE
Mod Crashes when Loading "mods Phase 1" PreInitialization - Redstone Arsenal

### ISSUE THREAD

**Issue by Craftbubi** [cyberstrawberry101/Omega-Adventure-Pack#7]
Mod Crashes when Loading "mods Phase 1" PreInitialization - Redstone Arsenal
It always Crases around 234-244/443 and I don't know why. I don't know if there's a crash report anywhere but it seems like it doesn't create one it just freezes the Window and even after an Hour it still is frozen. I really want to play the mod it looks like a lot of fun!

**Comment by ErickThePresident** [comment]
You probably need to allocate more ram. Check our website for more information on how to fix this issue. https://sites.google.com/view/omega-adventure-pack
