### ISSUE TITLE
Crashes when loading into title screen

### ISSUE THREAD

**Issue by my1st66mustang** [cyberstrawberry101/Omega-Adventure-Pack#9]
Unfortunately after I crashed the game by rebounding waila in-game it now crashes whenever I launch the game and it gets to the main menu screen. I have had this issue in older versions and was only able to resolve it after multiple reinstalls. Please help me with this, I attached the crash text file to this post.
[crash-2020-01-31_18.37.03-client.txt](https://github.com/cyberstrawberry101/Omega-Adventure-Pack/files/4142087/crash-2020-01-31_18.37.03-client.txt)

**Comment by cyberstrawberry101** [comment]
Assigned issue to @ErickThePresident and @powerhungryring

**Comment by cyberstrawberry101** [comment]
Resolved by @powerhungryring
